### ISSUE TITLE
`numpy` is not specified as a dependency

### ISSUE THREAD

**Issue by ionicsolutions** [operatorai/modelstore#172]
Encountered with modelstore version 0.0.74

To reproduce:

```shell
# create a new environment (Python 3.8)
python -m venv env
source env/bin/activate

# install modelstore and GCP CLI
pip install modelstore google-cloud-storage


python
Python 3.8.8 (default, Apr  4 2021, 16:02:17) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from modelstore import ModelStore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kilian/Documents/Ulm/GitHub/modelstorereplica/env/lib/python3.8/site-packages/modelstore/__init__.py", line 3, in <module>
    from modelstore.model_store import ModelStore
  File "/home/kilian/Documents/Ulm/GitHub/modelstorereplica/env/lib/python3.8/site-packages/modelstore/model_store.py", line 23, in <module>
    from modelstore.models.managers import iter_libraries, matching_managers, get_manager
  File "/home/kilian/Documents/Ulm/GitHub/modelstorereplica/env/lib/python3.8/site-packages/modelstore/models/managers.py", line 17, in <module>
    from modelstore.models.annoy import AnnoyManager
  File "/home/kilian/Documents/Ulm/GitHub/modelstorereplica/env/lib/python3.8/site-packages/modelstore/models/annoy.py", line 18, in <module>
    from modelstore.models.model_manager import ModelManager
  File "/home/kilian/Documents/Ulm/GitHub/modelstorereplica/env/lib/python3.8/site-packages/modelstore/models/model_manager.py", line 22, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

Output of `pip freeze`:

```
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.1.3
gitdb==4.0.9
GitPython==3.1.27
google-api-core==2.7.3
google-auth==2.6.6
google-cloud-core==2.3.0
google-cloud-storage==2.3.0
google-crc32c==1.3.0
google-resumable-media==2.3.2
googleapis-common-protos==1.56.0
idna==3.3
joblib==1.1.0
modelstore==0.0.74
protobuf==3.20.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.27.1
rsa==4.8
six==1.16.0
smmap==5.0.0
tqdm==4.64.0
urllib3==1.26.9
```

**Comment by nlathia** [comment]
Thanks 🙌 I've approved & merged your PR.
